added automated cloudformation cleanup to bootstrap; fixed port mismatch in ingress

diff --git a/.github/workflows/2_app_build_deploy.yaml b/.github/workflows/2_app_build_deploy.yaml
--- a/.github/workflows/2_app_build_deploy.yaml
+++ b/.github/workflows/2_app_build_deploy.yaml
@@ -284,6 +284,54 @@ jobs:
     #         --query "StandardErrorContent"
     #     fi
 
+    - name: clean-up-leftover-cloud-formation-stacks
+      shell: bash
+      continue-on-error: true
+      run: |  
+        set +e
+
+        # Capture command id
+        COMMAND_ID=$(aws ssm send-command \
+          --document-name "AWS-RunShellScript" \
+          --instance-ids ${{ steps.extract.outputs.bastion_id }} \
+          --comment "clean up orphaned CloudFormation stacks" \
+          --parameters commands=["/usr/local/src/bootstrap/cloudformation-cleanup.sh"] \
+          --region ${{ vars.AWS_REGION }} \
+          --query "Command.CommandId" \
+          --output text)
+
+        echo "Command (ID="$COMMAND_ID") submitted to bastion host. Waiting for completion..."
+
+        aws ssm wait command-executed \
+          --command-id "$COMMAND_ID" \
+          --instance-id ${{ steps.extract.outputs.bastion_id }} \
+          --region ${{ vars.AWS_REGION }}
+        WAIT_STATUS=$?
+
+        # set -e
+
+        # Wait until command is executed
+        if [[ "$WAIT_STATUS" -eq 0 ]]; then
+          # Get output 
+          echo "✅ Command succeeded. Fetching command output from bastion..."
+          aws ssm get-command-invocation \
+            --command-id "$COMMAND_ID" \
+            --instance-id ${{ steps.extract.outputs.bastion_id }} \
+            --region ${{ vars.AWS_REGION }} \
+            --output text \
+            --query "StandardOutputContent"
+
+        else
+          # Get error(s)
+          echo "❌ Command failed. Fetching error output (if any) from bastion..."
+          aws ssm get-command-invocation \
+            --command-id "$COMMAND_ID" \
+            --instance-id ${{ steps.extract.outputs.bastion_id }} \
+            --region ${{ vars.AWS_REGION }} \
+            --output text \
+            --query "StandardErrorContent"
+        fi
+
     - name: install-alb-controller-through-bastion
       shell: bash
       continue-on-error: true
