corrected bastion arn param in GHA flow

diff --git a/.github/workflows/2_app_build_deploy.yaml b/.github/workflows/2_app_build_deploy.yaml
--- a/.github/workflows/2_app_build_deploy.yaml
+++ b/.github/workflows/2_app_build_deploy.yaml
@@ -169,12 +169,45 @@ jobs:
     - name: patch-aws-auth-in-eks
       shell: bash
       run: |
-        aws ssm send-command \
+        set +e
+
+        # Capture command id
+        COMMAND_ID=$(aws ssm send-command \
           --document-name "AWS-RunShellScript" \
           --instance-ids "${{ steps.extract.outputs.bastion_id }}" \
           --comment "patch aws-auth in eks" \
           --parameters '{"commands":["aws eks update-kubeconfig --region ${{ vars.AWS_REGION }} --name ${{ steps.extract.outputs.cluster_name }}","eksctl create iamidentitymapping --cluster ${{ steps.extract.outputs.cluster_name }} --region ${{ vars.AWS_REGION }} --arn ${{ steps.extract.outputs.bastion_role_arn }} --group system:masters --username ${{ steps.extract.outputs.bastion_username }}"]}' \
-          --region "${{ vars.AWS_REGION }}"
+          --region "${{ vars.AWS_REGION }}")
+
+        echo "Command (ID="$COMMAND_ID") submitted to bastion host. Waiting for completion..."
+
+        aws ssm wait command-executed \
+          --command-id "$COMMAND_ID" \
+          --instance-id ${{ steps.extract.outputs.bastion_id }} \
+          --region ${{ vars.AWS_REGION }}
+        WAIT_STATUS=$?
+
+        # Wait until command is executed
+        if [ "$WAIT_STATUS" -eq 0]; then
+          # Get output 
+          echo "✅ Command succeeded. Fetching command output from bastion..."
+          aws ssm get-command-invocation \
+            --command-id "$COMMAND_ID" \
+            --instance-id ${{ steps.extract.outputs.bastion_id }} \
+            --region ${{ vars.AWS_REGION }} \
+            --output text \
+            --query "StandardOutputContent"
+
+        else
+          # Get error(s)
+          echo "❌ Command failed. Fetching error output (if any) from bastion..."
+          aws ssm get-command-invocation \
+            --command-id "$COMMAND_ID" \
+            --instance-id ${{ steps.extract.outputs.bastion_id }} \
+            --region ${{ vars.AWS_REGION }} \
+            --output text \
+            --query "StandardErrorContent"
+        fi
 
     - name: install-remote-bastion
       shell: bash
