GHA script corrected

diff --git a/.github/workflows/2_app_build_deploy.yaml b/.github/workflows/2_app_build_deploy.yaml
--- a/.github/workflows/2_app_build_deploy.yaml
+++ b/.github/workflows/2_app_build_deploy.yaml
@@ -161,7 +161,11 @@ jobs:
         done
 
     - name: install-remote-bastion
+      shell: bash
+      continue-on-error: true
       run: |  
+        set +e
+
         # Capture command id
         COMMAND_ID=$(aws ssm send-command \
           --document-name "AWS-RunShellScript" \
@@ -182,28 +186,58 @@ jobs:
 
         echo "Command (ID="$COMMAND_ID") submitted to bastion host. Waiting for completion..."
 
-        # Wait until command is executed
         aws ssm wait command-executed \
           --command-id "$COMMAND_ID" \
           --instance-id ${{ steps.extract.outputs.bastion_id }} \
           --region ${{ vars.AWS_REGION }}
+        WAIT_STATUS=$?
+
+        # set -e
+
+        # Wait until command is executed
+        if [ "$WAIT_STATUS" -eq 0]; then
+          # Get output 
+          echo "✅ Command succeeded. Fetching command output from bastion..."
+          aws ssm get-command-invocation \
+            --command-id "$COMMAND_ID" \
+            --instance-id ${{ steps.extract.outputs.bastion_id }} \
+            --region ${{ vars.AWS_REGION }} \
+            --output text \
+            --query "StandardOutputContent"
+
+        else
+          # Get error(s)
+          echo "❌ Command failed. Fetching error output (if any) from bastion..."
+          aws ssm get-command-invocation \
+            --command-id "$COMMAND_ID" \
+            --instance-id ${{ steps.extract.outputs.bastion_id }} \
+            --region ${{ vars.AWS_REGION }} \
+            --output text \
+            --query "StandardErrorContent"
+        fi
+
+        # Wait until command is executed
+        # aws ssm wait command-executed \
+        #   --command-id "$COMMAND_ID" \
+        #   --instance-id ${{ steps.extract.outputs.bastion_id }} \
+        #   --region ${{ vars.AWS_REGION }}
 
         # Get output / error(s)
-        echo "Fetching command output from bastion..."
-        aws ssm get-command-invocation \
-          --command-id "$COMMAND_ID" \
-          --instance-id ${{ steps.extract.outputs.bastion_id }} \
-          --region ${{ vars.AWS_REGION }} \
-          --output text \
-          --query "StandardOutputContent"
+        # echo "Fetching command output from bastion..."
+        # aws ssm get-command-invocation \
+        #   --command-id "$COMMAND_ID" \
+        #   --instance-id ${{ steps.extract.outputs.bastion_id }} \
+        #   --region ${{ vars.AWS_REGION }} \
+        #   --output text \
+        #   --query "StandardOutputContent"
 
-        echo "Fetching error output (if any) from bastion..."
-        aws ssm get-command-invocation \
-          --command-id "$COMMAND_ID" \
-          --instance-id ${{ steps.extract.outputs.bastion_id }} \
-          --region ${{ vars.AWS_REGION }} \
-          --output text \
-          --query "StandardErrorContent"
+        # echo "Fetching error output (if any) from bastion..."
+        # aws ssm get-command-invocation \
+        #   --command-id "$COMMAND_ID" \
+        #   --instance-id ${{ steps.extract.outputs.bastion_id }} \
+        #   --region ${{ vars.AWS_REGION }} \
+        #   --output text \
+        #   --query "StandardErrorContent"
 
     # - name: install-remote
     #   run: |
