corrected conditional

diff --git a/.github/workflows/2_app_build_deploy.yaml b/.github/workflows/2_app_build_deploy.yaml
--- a/.github/workflows/2_app_build_deploy.yaml
+++ b/.github/workflows/2_app_build_deploy.yaml
@@ -215,16 +215,20 @@ jobs:
           --region ${{ vars.AWS_REGION }} \
           --query "Command.CommandId" \
           --output text)
+        
+        set +e
 
         echo "Command submitted to bastion host. Waiting for completion..."
-
-        # Wait until command is executed
-        if aws ssm wait command-executed \
+        aws ssm wait command-executed \
           --command-id "$COMMAND_ID" \
           --instance-id ${{ steps.extract.outputs.bastion_id }} \
-          --region ${{ vars.AWS_REGION }}; then
+          --region ${{ vars.AWS_REGION }}
+        WAIT_STATUS=$?
+
+        # Wait until command is executed
+        if [ "$WAIT_STATUS" -eq 0]; then
           # Get output 
-          echo "Fetching command output from bastion..."
+          echo "✅ Command succeeded. Fetching command output from bastion..."
           aws ssm get-command-invocation \
             --command-id "$COMMAND_ID" \
             --instance-id ${{ steps.extract.outputs.bastion_id }} \
@@ -234,7 +238,7 @@ jobs:
 
         else
           # Get error(s)
-          echo "Fetching error output (if any) from bastion..."
+          echo "❌ Command failed. Fetching error output (if any) from bastion..."
           aws ssm get-command-invocation \
             --command-id "$COMMAND_ID" \
             --instance-id ${{ steps.extract.outputs.bastion_id }} \
@@ -242,6 +246,8 @@ jobs:
             --output text \
             --query "StandardErrorContent"
         fi
+
+        set -e
 
         # # Get output / error(s)
         # echo "Fetching command output from bastion..."
